refactor: email test cases
fabian-hiller/valibot pull request #276
Opened 2023-11-28 17:01 UTC by ariskemper

Here is my proposal for email test cases. I fixed regex so it supports
max 64 chars in local part of email value and 255 chars in domain part.

2023-11-29 07:44 UTC, ariskemper commented
@fabian-hiller We could wrap the tests in another describe for grouping. I was also thinking to create a helper function which takes as an argument validate._parse(value).issues or validate._parse(value).output and returns true or false.
Would be nicer to read test like 

`expect(isValidParse(validate._parse(value))).toBeTruthy();`

or

`expect(isValidParse(validate._parse(value))).toBeFalsy();`

2023-11-29 15:21 UTC, fabian-hiller commented
I think I like the grouping but I am not sure about the utility functions. I like that the tests show the raw code, but on the other hand I also see the advantage of making the code more readable and simple. If we were to create a helper function for this, I would choose the following API:

```ts
expect(isValidParse(validate, value)).toBeTruthy();
expect(isValidParse(validate, value)).toBeFalsy();
```

Do you have an idea for alternative names for the utility function? Maybe `passes`, `validate` or `parse`. I am looking for a word that makes the whole API more readable.

2023-11-29 19:49 UTC, ariskemper commented
@fabian-hiller i also like tests showing raw code, but readable tests are also important so my suggestion is following:

```
const emailValidate = email();
expect(parse(emailValidate, value)).toBeTruthy();
expect(parse(emailValidate, value)).toBeFalsy();
```

2023-11-30 05:05 UTC, fabian-hiller commented
Looks good to me. Feel free to implement this for some tests so we can compare. A disadvantage of this approach is that not everything can be covered with `true` and `false` and we still have to resort to raw code in some cases.

2023-12-01 14:18 UTC, fabian-hiller commented on library/src/regex.ts
> +  /^[\w+-]{1,64}(?:\.[\w+-]{1,64})*@[\da-z]{1,255}(?:[.-][\da-z]{1,255})*\.[a-z]{2,}$/iu;
Our regex deliberately tries not to conform to the standard. However, there is a discussion in #204 about whether we want to add a separate validation function for this.

2023-12-01 16:01 UTC, ariskemper commented on library/src/regex.ts
> +  /^[\w+-]{1,64}(?:\.[\w+-]{1,64})*@[\da-z]{1,255}(?:[.-][\da-z]{1,255})*\.[a-z]{2,}$/iu;
@fabian-hiller i reverted email Regex and removed associated tests. In the future, it could be changed, if agreed.

2023-12-08 09:08 UTC, ariskemper commented
@fabian-hiller what do you think about this PR and parseValidation? If you agree, we could merge it and i refactor current mac and bic tests?

2023-12-15 08:44 UTC, ariskemper commented
@fabian-hiller any update on this?

2023-12-15 17:30 UTC, fabian-hiller commented
It's on my list. I have not forgotten. By the end of next week I will be working full time on Valibot for the next few weeks. I expect big progress on the source code and documentation.

2023-12-15 18:05 UTC, ariskemper commented
@fabian-hiller i was thinking maybe that we could have some status in validation, which is setled, based on validation true, false, besides issues array.

2023-12-16 01:11 UTC, fabian-hiller commented
What is the advantage of such an status key in your eyes? So far I have consciously decided against it for the internal code because it was not necessary. For external use of a schema, for example with `safeParse`, such a status is returned with `.success`.

2023-12-22 00:38 UTC, fabian-hiller requested changes
I like the more fine-grained tests with a separate message for each case. I also like the 3-layer system (the grouping) with the nested `describe`. I am not sure about the `parseValidation` function, because I think it is better not to add an abstraction here. Currently I tend not to use it. Also, instead of just testing `.output`, I think that I would prefer if we test the entire object returned by `email`. Feel free to give me feedback on this.

2024-01-01 18:03 UTC, fabian-hiller commented
Thank you again for your contribution. I will try to review it the next days and give you feedback.

2024-01-05 15:56 UTC, fabian-hiller requested changes
This PR looks good now. There is only one thing I would change. I think instead of just testing the output, we should test the whole object returned by `._parse`. This makes the tests safer. What do you think?

```ts
// Old
test('should pass standard email', () => {
  const value = 'email@example.com';
  expect(validate._parse(value).output).toBe(value);
});

// New
test('should pass standard email', () => {
  const value = 'email@example.com';
  expect(validate._parse(value)).toEqual({ output: value });
});
```

2024-01-05 15:58 UTC, fabian-hiller commented
Once this PR is merged, I recommend creating another PR for the tests of the `string` schema function, and then we can rework the tests of the entire library.

2024-01-05 20:23 UTC, ariskemper commented
@fabian-hiller i agree to the recommendation to compare with output object.

2024-01-10 18:04 UTC, fabian-hiller commented
Thanks for updating this PR! I will review it again next week and probably merge it.

2024-01-14 11:00 UTC, ariskemper commented
@fabian-hiller please check PR https://github.com/fabian-hiller/valibot/pull/366 for string schema refactored tests.

2024-01-30 16:32 UTC, fabian-hiller commented
Please have a look an review my changes. Note: I have removed the "should return custom error message" test because after the refactor of #397 we will pass the [entire context](https://github.com/fabian-hiller/valibot/blob/feat-i18n/library/src/validations/email/email.ts#L39) to `actionIssue`. With "should contain the message argument" we ensure that the messages is part of the context.

2024-01-30 16:34 UTC, fabian-hiller approved these changes

2024-02-12 16:38 UTC, fabian-hiller commented on library/src/validations/email/email.test.ts
> +      expect(email()).toMatchObject({
Is `.toMatchObject()` less strict than `.toEqual()`? Why do you choose it here?

2024-04-23 16:13 UTC, fabian-hiller commented
Thank you again for this PR Aris! I added your tests to the rewrite of Valibot in this [commit](https://github.com/fabian-hiller/valibot/pull/502/commits/8023fea347c266f604285f61736b40729195d4cc).

2024-04-23 16:13 UTC, closed without merging