feat(i18n): add Simplified Chinese
fabian-hiller/valibot pull request #419
Opened 2024-02-06 08:23 UTC by xcfox

add Simplified Chinese for `@valibot/i18n`

2024-02-06 16:27 UTC, fabian-hiller commented
Thank you very much for this contribution! Do you know another native speaker who could review your translations for me?

2024-02-06 18:18 UTC, fabian-hiller commented
Can you explain the difference between Simplified Chinese (zh-CN) and Chinese (zh)?

2024-02-07 04:38 UTC, xcfox commented
> Can you explain the difference between Simplified Chinese (zh-CN) and Chinese (zh)?

Modern Chinese is divided into Simplified Chinese and Traditional Chinese. Simplified Chinese and Traditional Chinese are two ways of writing the same Chinese character. Simplified Chinese is popular in Mainland China, Singapore and Malaysia, while Traditional Chinese is popular in Taiwan Province of China and Hong Kong SAR of China.

现代中文分为简体中文和繁体中文。简体和繁体是同一个汉字的两种写法。简体中文在中国大陆、新加坡、马来西亚流行，繁体中文在中国台湾省、中国香港流行。

現代中文分為簡體中文和繁體中文。簡體和繁體是同一個漢字的兩種寫法。簡體中文在中國大陸、新加坡、馬來西亞流行，繁體中文在中國臺灣省、中國香港流行。

2024-02-07 12:14 UTC, 0712uu requested changes
I am a native speaker of Chinese. I have made some review.

2024-02-07 12:14 UTC, 0712uu commented on packages/i18n/src/zh-CN.ts
> +    finite:         (issue) => `无效的无限值：输入为 ${issue.received}`,
这里应该是“有限的”

2024-02-07 14:20 UTC, xcfox commented
The misstake is fixed

2024-02-07 15:23 UTC, fabian-hiller commented
I will review it in the next days!

2024-02-08 22:49 UTC, fabian-hiller commented
Could one or both of you also review the `zh-TW` translations in #427?

2024-02-09 04:27 UTC, Mini-ghost commented
In fact, Traditional Chinese and Simplified Chinese not only have different writing methods, but they also feature distinct idiomatic expressions.

After reading the Simplified Chinese translation, I believe it is great. Additionally, the PR has been reviewed by Simplified Chinese users, and I believe the results are trustworthy.

2024-02-09 15:31 UTC, fabian-hiller commented
Thank you for your review!

2024-02-09 16:59 UTC, merged