feat(i18n): add Korean translations
fabian-hiller/valibot pull request #429
Opened 2024-02-09 04:54 UTC by dodok8

Add Korean for @valibot/i18n

2024-02-09 15:33 UTC, fabian-hiller commented
Thank you for this PR! Do you know another native speaking developer that could review the translations for me?

2024-02-10 02:44 UTC, dodok8 commented
I asked my fellow developers for a review. However, this weekend is one of  the biggest holiday of Korea, Lunar New Year. So it might take some time.

2024-02-10 02:48 UTC, fabian-hiller commented
Thank you and no worries!

2024-02-10 04:14 UTC, baekrang256 approved these changes
Seems to be done well. I think it's good to go 😄

2024-02-10 04:16 UTC, fabian-hiller commented
Thank you for your review!

2024-02-10 07:44 UTC, 2paperstar requested changes

2024-02-10 07:44 UTC, 2paperstar commented on packages/i18n/src/kr.ts
> +    isoWeek: (issue) => `유효하지 않은 요일: ${issue.received} 을(를) 받았습니다.`,
korean translation means "day of week" but this library intends "iso week" (yyyy-Www)
reference: https://github.com/fabian-hiller/valibot/blob/main/library/src/validations/isoWeek/isoWeek.ts

2024-02-10 07:44 UTC, 2paperstar commented on packages/i18n/src/kr.ts
> +    isoWeek: (issue) => `유효하지 않은 요일: ${issue.received} 을(를) 받았습니다.`,
I think `유효하지 않은 주` is better

2024-02-10 07:44 UTC, 2paperstar commented on packages/i18n/src/kr.ts
> +    hexColor: (issue) => `유효하지 않은 hex 색상: ${issue.received} 을(를) 받았습니다.`,
hex color is most translated as `헥스 코드` than `hex 색상`, but `hex 색상` is also good.

2024-02-10 10:21 UTC, 2paperstar approved these changes
it seems good 👍

2024-02-10 17:31 UTC, fabian-hiller commented
Thank you! I plan to merge this PR today.

2024-02-11 17:50 UTC, fabian-hiller commented
Would it be wrong to remove the dot at the end of each sentence? If so, I would merge the PR that way. If not, I would remove the dot to be consistent with the other translations.

2024-02-11 18:08 UTC, 2paperstar commented
> Would it be wrong to remove the dot at the end of each sentence? If so, I would merge the PR that way. If not, I would remove the dot to be consistent with the other translations.

No. It’s ok to remove them.

2024-02-11 18:20 UTC, merged