Merge remote-tracking branch 'refs/remotes/origin/main'
fabian-hiller/valibot pull request #434
Opened 2024-02-11 18:39 UTC by AndreyYolkin

2024-02-11 18:42 UTC, fabian-hiller commented
Thank you very much! I will wait for the review of the linked persons.

2024-02-11 18:47 UTC, Hekikai commented on packages/i18n/src/ru.ts
> +    excludes:       (issue) => `Неправильный исключение: ожидалось ${issue.expected}, получено ${issue.received}`,
Род несоответствует

2024-02-11 18:47 UTC, Hekikai commented on packages/i18n/src/ru.ts
> +    includes:       (issue) => `Неправильный вхождение: ожидалось ${issue.expected}, получено ${issue.received}`,
Род несоответствует

2024-02-11 18:47 UTC, Hekikai commented on packages/i18n/src/ru.ts
> +    maxValue:       (issue) => `Неправильное значение: ожидалось ${issue.expected}, получено ${issue.received}`,
Тут и на 48 строчке одинаковое значение. Мб уточнить про максимальное/минимальное?

2024-02-11 18:48 UTC, Hekikai commented
A few things to change and it can be merged ;)

2024-02-11 18:50 UTC, AndreyYolkin commented on packages/i18n/src/ru.ts
> +    maxValue:       (issue) => `Неправильное значение: ожидалось ${issue.expected}, получено ${issue.received}`,
В оригинале совпадают тоже, смотри https://github.com/fabian-hiller/valibot/blob/cf1dc5afb2cf0725321d632e3f71c179ca784f53/packages/i18n/src/en.ts#L43

2024-02-11 19:16 UTC, Hekikai commented on packages/i18n/src/ru.ts
> +    maxValue:       (issue) => `Неправильное значение: ожидалось ${issue.expected}, получено ${issue.received}`,
Все понял, спасиба

2024-02-11 19:21 UTC, AndreyYolkin commented
We've resolved all issues with translations

2024-02-11 20:48 UTC, fabian-hiller commented
Thank you both very much!

2024-02-11 21:56 UTC, Sdju requested changes
Отличная работа!
Заранее прошу прощения: тут много узких/душных моментов от себя. Многие из них можно оставить без исправления. Моя задача была подсветить что смогу, а там уже решай, что из этого принять или нет

2024-02-11 21:56 UTC, Sdju commented on packages/i18n/src/ru.ts
> +  schema:           (issue) => `Неправильный тип: ожидался ${issue.expected}, получено ${issue.received}`,
Вот тут не знаю как отнестись. Везде нет согласованности между первой частью и второй по роду. Только в schema и mimeType "ожидался". Другие формы не используются

2024-02-11 21:56 UTC, Sdju commented on packages/i18n/src/ru.ts
> +    multipleOf:     (issue) => `Неправильное произведение: ожидалось ${issue.expected}, получено ${issue.received}`,
В изначальной версии было "multiple" это "кратное число". Произведение было бы "product"

2024-02-11 21:56 UTC, Sdju commented on packages/i18n/src/ru.ts
> +    bytes:          (issue) => `Неправильное количество байт: ожидалось ${issue.expected}, получено ${issue.received}`,
Короч духота дикая. Просто стало любопытно самому. Короче, [предлагают использовать](https://gramota.ru/spravka/vopros/240564#question) "количество байтов". Не настаиваю на исправлении

2024-02-11 22:42 UTC, AndreyYolkin commented on packages/i18n/src/ru.ts
> +    hexadecimal:    (issue) => `Неправильное шестнадцатеричное значение: получено ${issue.received}`,
Тут смотрел на перевод с украинского, код, число и значение взяты оттуда

2024-02-11 22:42 UTC, AndreyYolkin commented on packages/i18n/src/ru.ts
> +    octal:          (issue) => `Неправильный восьмеричный код: получено ${issue.received}`,
Тут аналогично

2024-02-11 22:45 UTC, AndreyYolkin commented on packages/i18n/src/ru.ts
> +    excludes:       (issue) => `Неправильное исключение: ожидалось ${issue.expected}, получено ${issue.received}`,
Надо тогда подумать. "Лишнее значение"?

2024-02-11 22:47 UTC, AndreyYolkin commented on packages/i18n/src/ru.ts
> +  schema:           (issue) => `Неправильный тип: ожидался ${issue.expected}, получено ${issue.received}`,
Наверное лучше поменять и в других местах на "ожидался", MAC и IMEI как правильно будут?

2024-02-11 22:53 UTC, AndreyYolkin commented on packages/i18n/src/ru.ts
> +    includes:       (issue) => `Неправильное вхождение: ожидалось ${issue.expected}, получено ${issue.received}`,
В пару "Недостающее значение"?

2024-02-11 23:51 UTC, Sdju commented on packages/i18n/src/ru.ts
> +    hexadecimal:    (issue) => `Неправильное шестнадцатеричное значение: получено ${issue.received}`,
Все равно странно почему octal / decimal / hexadecimal имеют разную трактовку. Хотелось бы все-таки, наверное, к одному виду любому привести

2024-02-11 23:53 UTC, Sdju commented on packages/i18n/src/ru.ts
> +    excludes:       (issue) => `Неправильное исключение: ожидалось ${issue.expected}, получено ${issue.received}`,
Хотелось бы увидеть, что там вообще выводится. Так как само правило странно формулируется: "проверка что заданная последовательность не является подпоследовательностью входных данных"

2024-02-12 00:00 UTC, Sdju commented on packages/i18n/src/ru.ts
> +    includes:       (issue) => `Неправильное вхождение: ожидалось ${issue.expected}, получено ${issue.received}`,
Тут без понятия нужно ли править. Звучит и с таким вариантов неплохо

2024-02-12 03:26 UTC, fabian-hiller commented
Are you done with all the changes? Is it ready to merge, or should someone else do a final review first?

2024-02-12 10:36 UTC, Sdju commented
> Are you done with all the changes? Is it ready to merge, or should someone else do a final review first?

I'm still waiting for some answers from the PR author

2024-02-12 11:47 UTC, AndreyYolkin commented on packages/i18n/src/ru.ts
> +    hexadecimal:    (issue) => `Неправильное шестнадцатеричное значение: получено ${issue.received}`,
Давай значение, для чисел есть integer, по идее

2024-02-12 11:52 UTC, AndreyYolkin commented on packages/i18n/src/ru.ts
> +    excludes:       (issue) => `Неправильное исключение: ожидалось ${issue.expected}, получено ${issue.received}`,
Может быть тогда тоже "Неправильное вхождение"? По сути верно

2024-02-12 15:08 UTC, Sdju commented on packages/i18n/src/ru.ts
> +    excludes:       (issue) => `Неправильное исключение: ожидалось ${issue.expected}, получено ${issue.received}`,
Давай так

2024-02-12 15:09 UTC, Sdju commented on packages/i18n/src/ru.ts
> +    includes:       (issue) => `Неправильное вхождение: ожидалось ${issue.expected}, получено ${issue.received}`,
тогда оставляем текущий вариант

2024-02-12 16:26 UTC, AndreyYolkin commented
Now we are completely ready

2024-02-12 17:24 UTC, merged