feat(i18n): add Portuguese translations
fabian-hiller/valibot pull request #509
Opened 2024-04-07 14:56 UTC by Makley-Tibola-Trichez

Add Portuguese for @valibot/i18n

2024-04-08 15:16 UTC, fabian-hiller commented
Thank you for this PR! Do you know another native speaking developer that could review the translations for me?

2024-04-08 15:31 UTC, Makley-Tibola-Trichez commented
Yes, i'll ask someone to review and comment

2024-04-08 16:07 UTC, patrickpiccini requested changes

2024-04-08 16:07 UTC, patrickpiccini commented on packages/i18n/src/pt.ts
> +    size:           (issue) => `Tamanho inválido: Esperado ${issue.expected}, mas recebido ${issue.received}`,
`Tamanho inválido: Esperado ${issue.expected}, porém foi recebido ${issue.received}`

2024-04-08 16:07 UTC, patrickpiccini commented on packages/i18n/src/pt.ts
> +    startsWith:     (issue) => `Início inválido: Esperado ${issue.expected}, mas recebido ${issue.received}`,
`Início inválido: Esperado ${issue.expected}, porém foi recebido ${issue.received}`

2024-04-08 16:07 UTC, patrickpiccini commented on packages/i18n/src/pt.ts
> +    value:          (issue) => `Valor inválido: Esperado ${issue.expected}, mas recebido ${issue.received}`,
`Valor inválido: Esperado ${issue.expected}, porém foi recebido ${issue.received}`

2024-04-08 16:25 UTC, Makley-Tibola-Trichez commented
I believe everything is fine, but another friend will review it later

2024-04-08 20:13 UTC, fabian-hiller commented
Thank you so much!

2024-04-09 01:02 UTC, darc591 approved these changes
LGTM 👍

2024-04-09 20:35 UTC, fabian-hiller commented
Thank you everyone for this contribution!

2024-04-09 20:35 UTC, merged