chore(i18n): add Indonesian (id) language support
fabian-hiller/valibot pull request #683
Opened 2024-06-29 15:39 UTC by risqiromadhoni

Added Indonesian translations for @valibot/i18n

2024-06-29 16:01 UTC, fabian-hiller commented
Thank you for this PR! Do you know another native speaking developer that could review the translations for me?

2024-07-15 21:39 UTC, fabian-hiller commented
Any updates on this PR?

2024-07-16 02:37 UTC, smujaddid commented
> Thank you for this PR! Do you know another native speaking developer that could review the translations for me?

I'm also a native Indonesian speaker. I can help review this at the weekend if you need it.

2024-07-16 08:51 UTC, fabian-hiller commented
That would be great! Thank you very much!

2024-07-21 13:59 UTC, smujaddid requested changes
I think these translations along with my suggestions should be enough for direct or word-to-word translations.
For alternative, we can use different words for these messages, which doesn't have to be word-to-word translations. For example:
```
integer: (issue) => `Bukan integer. Menerima ${issue.received}`
```

2024-07-21 14:26 UTC, risqiromadhoni commented on packages/i18n/src/id.ts
> +    hexadecimal:    (issue) => `Hexadecimal tidak valid: Menerima ${issue.received}`,
Updated @smujaddid

2024-07-21 14:26 UTC, risqiromadhoni commented on packages/i18n/src/id.ts
> +    multipleOf:     (issue) => `Banyak tidak valid: Diharapkan ${issue.expected} tetapi menerima ${issue.received}`,
Updated @smujaddid

2024-07-21 14:26 UTC, risqiromadhoni commented on packages/i18n/src/id.ts
> +    octal:          (issue) => `Octal tidak valid: Menerima ${issue.received}`,
Updated @smujaddid

2024-07-21 14:26 UTC, risqiromadhoni commented on packages/i18n/src/id.ts
> +    startsWith:     (issue) => `Awal tidak valid: Diharapkan ${issue.expected} tetapi menerima ${issue.received}`,
Updated @smujaddid

2024-07-21 14:26 UTC, risqiromadhoni commented on packages/i18n/src/id.ts
> +    endsWith:       (issue) => `Akhir tidak valid: Diharapkan ${issue.expected} tetapi menerima ${issue.received}`,
Updated @smujaddid

2024-07-21 14:26 UTC, risqiromadhoni commented on packages/i18n/src/id.ts
> +    isoDateTime:    (issue) => `Date-time tidak valid: Menerima ${issue.received}`,
Updated @smujaddid

2024-07-21 17:55 UTC, fabian-hiller commented
Does this PR look good to all of you now?

2024-07-22 00:33 UTC, smujaddid commented
> Does this PR look good to all of you now?

Yes, looking good to me.

2024-07-24 19:14 UTC, merged